In [47]:
import tkinter as tk
from tkinter import ttk
import sqlite3
fn=""
ln=""
mob=0

In [48]:
def regform(conn):
    windows = tk.Tk()
    windows.geometry('500x500')
    windows.title("REGISTRATION FORM")
    lbl_0 = ttk.Label(windows, text="REGISTRATION FORM",font=("Arial Rounded MT Bold",30))
    lbl_0.place(x=560,y=20)
    lbl_0.configure(foreground='white',background='black')



    lbl_1 = ttk.Label(windows, text="First Name",font=("bold",25))
    lbl_1.place(x=180,y=112)
    ent_1=ttk.Entry(windows,width=50)
    ent_1.place(x=380,y=128)
    ent_1.focus()



    lbl_2 = ttk.Label(windows, text="Last Name",font=("bold",25))
    lbl_2.place(x=850,y=112)
    ent_2=ttk.Entry(windows,width=50)
    ent_2.place(x=1040,y=126)



    lbl_3 = ttk.Label(windows, text="Birth  Date",font=("bold",25))
    lbl_3.place(x=180,y=212)
    combo_0 = ttk.Combobox(windows,width=10,state='readonly')
    combo_0['values']= ("Date",1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31)
    combo_0.current(0)
    combo_0.place(x=380,y=225)
    combo_1 = ttk.Combobox(windows,state='readonly')
    combo_1['values']= ("Month",'Januray','February','March','April','May','June','July','August','September','October','November','December')
    combo_1.current(0)
    combo_1.place(x=470,y=225)
    combo_2 = ttk.Combobox(windows,state='readonly')
    combo_2['values']= ("Year",2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030)
    combo_2.current(0)
    combo_2.place(x=620,y=225)




    lbl_4 = ttk.Label(windows, text="Gender",font=("bold",25))
    lbl_4.place(x=889,y=212)
    combo_3 = ttk.Combobox(windows,state='readonly')
    combo_3['values']= ("Select",'Male','Female','Others')
    combo_3.current(0)
    combo_3.place(x=1040,y=225)



    lbl_5 = ttk.Label(windows, text="Address",font=("bold",25))
    lbl_5.place(x=205,y=312)
    ent_3=ttk.Entry(windows,width=80)
    ent_3.place(x=380,y=325)
    lbl_6 = ttk.Label(windows, text="City",font=("bold",25))
    lbl_6.place(x=930,y=312)
    ent_4=ttk.Entry(windows,width=40)
    ent_4.place(x=1045,y=325)



    lbl_6 = ttk.Label(windows, text="State",font=("bold",25))
    lbl_6.place(x=240,y=400)
    combo_4 = ttk.Combobox(windows,state='readonly')
    combo_4['values']= ("Choose",'Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat'
    'Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra'
    'Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana'
    'Tripura','Uttar Pradesh','Uttarakhand','West Bengal')
    combo_4.current(0)
    combo_4.place(x=380,y=410)


    lbl_7 = ttk.Label(windows, text="Country",font=("bold",25))
    lbl_7.place(x=585,y=400)
    ent_5=ttk.Entry(windows,width=35)
    ent_5.place(x=745,y=415)



    lbl_8 = ttk.Label(windows, text="Zip code",font=("bold",25))
    lbl_8.place(x=1000,y=400)
    ent_6=ttk.Entry(windows,width=30)
    ent_6.place(x=1170,y=415)


    lbl_9 = ttk.Label(windows, text="Email-Id",font=("bold",25))
    lbl_9.place(x=205,y=500)
    ent_7=ttk.Entry(windows,width=50)
    ent_7.place(x=380,y=515)

    lbl_10 = ttk.Label(windows, text="Mobile Number",font=("bold",25))
    lbl_10.place(x=800,y=500)
    ent_8=ttk.Entry(windows,width=40)
    ent_8.place(x=1080,y=515)
    fn=ent_1.get()
    ln=ent_2.get()
    mob=ent_8.get()

    def clicked():
        link="C:/Users/SHAMS TABREZ/Desktop/new/databaseall/"
        conn=sqlite3.connect(link+'ProjectDatabase.db')
        try:
            conn.execute('''CREATE TABLE projectdatabase1(
                         ID INTEGER PRIMARY KEY AUTOINCREMENT,
                         FIRSTNAME    TEXT   NOT NULL,
                         LASTNAME    TEXT    NOT NULL,
                         BIRTHDATE      INT    NOT NULL,
                         GENDER          CHAR(50),
                         ADDRESS         CHAR(50),
                         CITY            CHAR(50),
                         STATE           CHAR(50),
                         COUNTRY         CHAR(50),
                         ZIPCODE        CHAR(50),
                         EMAILID        CHAR(50),
                         MOBILENUMBER   INT   NOT NULL);
                         ''')
        except:
            pass
        val=(ent_1.get(),ent_2.get(),combo_0.get()+"-"+combo_1.get()+"-"+combo_2.get(),combo_3.get(),ent_3.get(),ent_4.get(),combo_4.get(),ent_5.get(),ent_6.get(),ent_7.get(),ent_8.get())
        sql="INSERT INTO PROJECTDATABASE1 (FIRSTNAME,LASTNAME,BIRTHDATE,GENDER,ADDRESS,CITY,STATE,COUNTRY,ZIPCODE,EMAILID,MOBILENUMBER) VALUES(?,?,?,?,?,?,?,?,?,?,?)"
        conn.execute(sql,val);
        conn.commit()








        print(ent_1.get(),ent_2.get(),combo_0.get(),combo_1.get(),combo_2.get(),combo_3.get(),ent_3.get(),ent_4.get(),combo_4.get(),
             ent_5.get(),ent_6.get(),ent_7.get())
    btn = ttk.Button(windows, text="SUBMIT",command=clicked,width=35)
    btn.place(x=630,y=650)    
    windows.mainloop()

In [49]:
def update(conn):
    link="C:/Users/SHAMS TABREZ/Desktop/new/databaseall/"
    conn=sqlite3.connect(link+'ProjectDatabase.db')
    print(fn)
    try:
        mob=int(input("Enter Mobile number: "))
    except:
        pass
    
    try:
        conn.execute('''CREATE TABLE projectdatabase1(
                         ID INTEGER PRIMARY KEY AUTOINCREMENT,
                         FIRSTNAME    TEXT   NOT NULL,
                         LASTNAME    TEXT    NOT NULL,
                         BIRTHDATE      INT    NOT NULL,
                         GENDER          CHAR(50),
                         ADDRESS         CHAR(50),
                         CITY            CHAR(50),
                         STATE           CHAR(50),
                         COUNTRY         CHAR(50),
                         ZIPCODE        CHAR(50),
                         EMAILID        CHAR(50),
                         MOBILENUMBER   INT   NOT NULL);
                         ''')
    except:
        pass
      #  val=(ent_1.get(),ent_2.get(),combo_0.get()+"-"+combo_1.get()+"-"+combo_2.get(),combo_3.get(),ent_3.get(),ent_4.get(),combo_4.get(),ent_5.get(),ent_6.get(),ent_7.get(),ent_8.get())
       # '''sql="INSERT INTO PROJECTDATABASE1 (FIRSTNAME,LASTNAME,BIRTHDATE,GENDER,ADDRESS,CITY,STATE,COUNTRY,ZIPCODE,EMAILID,MOBILENUMBER) VALUES(?,?,?,?,?,?,?,?,?,?,?)"
        #conn.execute(sql,val);
        #conn.commit()'''

    
    
    
    
    sql="update projectdatabase1 set FirstName = ?, LastName = ?, where Mobilenumber= ?"
    val=(fn,ln,mob)
    conn.execute(sql,val);
    conn.commit()
#update(conn)

In [50]:
import tkinter as tk
from tkinter import ttk
import sqlite3
def warning(conn):
    windows = tk.Tk()
    windows.title("Warning!!")
    windows.geometry('350x200')
    lbl1 = ttk.Label(windows,text="Credential Error!!",font=("Georgia",20)).place(x=560,y=30)
    lbl2 = ttk.Label(windows,text="Want to Login Again or Signup?",font=("Georgia",20)).place(x=560,y=60)
    def login1():
        windows.destroy()
        login(conn)
    def regform1():
        windows.destroy()
        regform(conn)
    btn1=tk.Button(windows,text="LOGIN",width=15,font="Georgia",command=login1)
    btn1.place(x=570,y=250)
    btn2=tk.Button(windows,text="SIGN UP",width=15,font="Georgia",command=regform1)
    btn2.place(x=770,y=250)
def login(conn):
    windows = tk.Tk()
    windows.title("Log In Page")
    windows.geometry('350x200')
    lbl1 = ttk.Label(windows,text="STUDENT LOGIN",font=("Georgia",30))
    lbl1.place(x=560,y=30)
    lbl2 = ttk.Label(windows,text="EMAIL ID",font=("bold",12))
    lbl2.place(x=580,y=120)
    ent1=ttk.Entry(windows,width=30)
    ent1.place(x=700,y=120)
    lbl3 = ttk.Label(windows,text="MOBILE NUM",font=("bold",12))
    lbl3.place(x=580,y=160)
    ent2=ttk.Entry(windows,width=30)
    ent2.place(x=700,y=160)

    
    
    def clicked1():
        link="C:/Users/SHAMS TABREZ/Desktop/new/databaseall/"
        conn=sqlite3.connect(link+'ProjectDatabase.db')
        cursor=conn.execute("select EMAILID,MOBILENUMBER from projectdatabase1")
        em=[]
        mob=[]
        for row in cursor:
            em.append(row[0])
            mob.append(row[1])
        #print(em)
        #print(mob)
        try:
            if em.index(ent1.get()) == mob.index(int(ent2.get())):
                print("Success")
            else:
                #windows.destroy()
                clicked2()
        except:
            windows.destroy()
            warning(conn)

    def clicked2():
        windows.destroy()
        regform(conn)
    btn1=tk.Button(windows,text="LOGIN",width=15,font="Georgia",command=clicked1)
    btn1.place(x=570,y=250)
    btn2=tk.Button(windows,text="SIGN UP",width=15,font="Georgia",command=clicked2)
    btn2.place(x=770,y=250)

    windows.mainloop()
link="C:/Users/SHAMS TABREZ/Desktop/new/databaseall/"
conn=sqlite3.connect(link+'ProjectDatabase.db')

login(conn)